"""
Django settings for user_management project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# To keep secret keys in environment variables
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = str(os.getenv('SECRET_KEY'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UserConfig',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'user_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'user_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.google.GoogleOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login'


# social auth configs for github
SOCIAL_AUTH_GITHUB_KEY = str(os.getenv('GITHUB_KEY'))
SOCIAL_AUTH_GITHUB_SECRET = str(os.getenv('GITHUB_SECRET'))

# social auth configs for google
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = str(os.getenv('GOOGLE_KEY'))
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = str(os.getenv('GOOGLE_SECRET'))

# email configs
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = str(os.getenv('EMAIL_USER'))
EMAIL_HOST_PASSWORD = str(os.getenv('EMAIL_PASSWORD'))

SESSION_COOKIE_AGE = 60 * 60 * 24 * 30


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

FIREBASE_CONFIG = {
  "type": "service_account",
  "project_id": "app-user-credentials",
  "private_key_id": "7fa846a21df17d0e9689104f73b6e497607e0535",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDdFckoccNSjQbH\ncDNEt5LyYnePgjVTHEX7xY8sxJHnViy+g96C8291DcocI6V3F9XOyHkniiBmN7mN\n6iH8+qGfOGQ+rJOu4D/K3Q76BuAZtrXbXOVlK3JmlZYzgfBqSfSHAymwTuchB9i3\nKcnEsZcB+Fxj2+ArtxlSd+Xrg2NhezVHd6K+RX0vzFOXeJYIWG5ZPNnovANxzt+9\n8EMnpZ0/RQ7hn6xxzqlUs2k47z4kXgeqDhZcLbXQoNj5wCsA1FMuZMWMNubDR4Ot\nk71Y8FYmgAhLQV3jDiw2m3qrlhGM8bdFENk9qF2xLUEwtIG/68vdP+Erl9iTgFvU\nBMeAy/aNAgMBAAECggEAHs0ateZHkpgwQhfpJKE4uUkrpBQ9bqNJQr7u6AtI0oSI\nflBr7y2QMSwnJM14j4OEF6eJbY9KXUNVOCbO7mpSmxalrK+pcZsveAldPUs47Iwu\ngO3LzdEEQrODdhCb2IsOJMM1iykq/UiVEkuhnyQoyC78XDM1Y5HCVuF6aFnpPhrE\nR1JF1d82oPPc8cbxxJi/kl7dF9NaVsLRrlvLGK5v/NKjh56UTdWM+6K9jGmO8xWB\nh12PqFhdr6lTpqM9kSsYAs0N6v8JpigvnC4dhj5UeehSOlAIXpOZNXcNEtakEVKo\nKiQYL8Gye/SxBdng50m+C1d1sk750nMmOdRPr6qKFwKBgQD/kpUueedP3NfL4GpU\ntKuZjS0fBPzHUgtC5HdRAi8nYsDtHcUhSUNWmMzcQIUpkzagMUeAXJaSI8VDbYKO\nFMbjeKW3ucfHNZJJYkURwhVMJERWJhPG0VYj1ZdBglQNYqymFY9XcM+0C0h+/ojN\nc0dpQf6sMVsKL+qKaBtZ/bpilwKBgQDddHAjp3A7wkemv8O6rHh+aLYCgdOAa9OU\n90Nv07BzuSSOCkglV1fy6MTbo/J9EwM/BEaXoJG9viD0hvVlSI8bSnGF6Coo9G3r\ne8AesFUGnAbXNSNr2IIp93JQIJaRMl3PmLmPQzYpjXe4RPV4zF1bGp3imDnqJgr4\nLzydo8EoewKBgB4GB1Z9ZaohJIzD4VnwG5SfXCSfvl5gCgiitE2k9wsmc8mnTKg7\nZhi/PJnHTp1yuOEayO6QcfPbFep06/hrAm5olvc9cPW7GmNakwiiB0R5ojmIoZwi\nrX7qMam1eNBVvjiIod1A2HWrOaoJluKj30jDQvrRlYNd26zEzCnHP+UjAoGAL2KF\nyCtAqZjFihmIQP48fhfbsiejYNwxlrNdu6TZIbng53+ttke9Kt3BmZm3/ik+TZKV\npEYYSThQhuIFyhk/fcBtEBEATGkYyAVfs3FZkCN8lznojV/zYhVvYVPHw+O6DPyJ\n3+yqvzNlBYnD2IgqBZ9pXx3hboebW0WIO9bZMtcCgYEAiNrgsL+IyVA+qY/+5Zg1\nUYJnXp0LGWeQehadlV3zlQ4hTs6b7CgcO0J8TP1CqHLVUi9RXk5J78LyS7vbhUYA\nPNd4vrtuRB/6AHG6RMAzSAMvE7cH89XF1LpDcwjm6n3rzXmCw3MTpy6Rkn1BCmuz\nGZ9yqbhkkVXV7LojSI5CR80=\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-nch0j@app-user-credentials.iam.gserviceaccount.com",
  "client_id": "103589621320021594180",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-nch0j%40app-user-credentials.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}

FIREBASE_COLLECTION = 'images'
